# syntax=docker/dockerfile:1

# Use the official Python image as the base image
FROM python:3.10-slim AS a2rchi-base

# Set environment variables to avoid interactive prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Install build-essential package which includes g++ and other build tools
RUN apt-get update && \
apt-get install -y build-essential && \
apt-get clean && \
    rm -rf /var/lib/apt/lists/*
