# syntax=docker/dockerfile:1
ARG TAG=0.1
FROM swinney/a2rchi-base:latest AS chat
ENV PYTHONPATH=/root/A2rchi
EXPOSE 7861

RUN apt-get update && \
apt-get install -y libpq-dev && \
apt-get clean && \
rm -rf /var/lib/apt/lists/*


# Set the working directory inside the container
WORKDIR /root/A2rchi

# Copy only the necessary files for installing dependencies
COPY pyproject.toml requirements.txt ./

# Upgrade pip and install dependencies
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

CMD ["python", "-u", "a2rchi/bin/service_chat.py"]